Overhaul to handle SIGTERM properly, with orderly shutdown of aux processes.
* Top-level SIGTERM trap is after starting processes, to avoid app from
  inheriting it, so the app can receive SIGTERM for orderly dyno shutdown.

* SIGTERM is ignored by the subshells and by the auxiliary processes.

* FIFO is removed after the first exit_process, so that following writes
  won't be blocked (they'll write to an actual tmp file).

* Translate subshell SIGHUP to preferred per-process shutdown signal
  (SIGINT) rather than sending SIGINT to the subshell, since it tends to be
  squashed by the shell.

diff --git a/bin/start-pgbouncer-stunnel b/bin/start-pgbouncer-stunnel
--- a/bin/start-pgbouncer-stunnel
+++ b/bin/start-pgbouncer-stunnel
@@ -1,73 +1,135 @@
 #!/usr/bin/env bash
 # Adapted from https://github.com/ryandotsmith/nginx-buildpack/
 
-# Generate config files
-echo 'buildpack=pgbouncer at=config-gen-start'
-source bin/gen-pgbouncer-conf.sh
-echo 'buildpack=pgbouncer at=config-gen-end'
+main() {
+  declare psmgr=/tmp/pgbouncer-buildpack-wait
+  declare -A pids signals
 
-# Overwrite config vars with pgbouncer targets
-POSTGRES_URLS=${PGBOUNCER_URLS:-DATABASE_URL}
+  config-gen
 
-for POSTGRES_URL in $POSTGRES_URLS
-do
-  echo "Overriding ${POSTGRES_URL} config var"
-  eval ${POSTGRES_URL}=\$${POSTGRES_URL}_PGBOUNCER
-done
+  # Use named pipe to detect exit of any subprocess.
+  rm -f "$psmgr"
+  mkfifo "$psmgr"
 
-# Use named pipes to detect exit of any sub process
-psmgr=/tmp/pgbouncer-buildpack-wait
-rm -f $psmgr
-mkfifo $psmgr
+  # Start processes.
+  aux-start stunnel SIGINT vendor/stunnel/bin/stunnel vendor/stunnel/stunnel-pgbouncer.conf
+  aux-start pgbouncer SIGINT vendor/pgbouncer/bin/pgbouncer vendor/pgbouncer/pgbouncer.ini
+  app-start SIGTERM "$@"
+  pid=$!
 
-# Do not exit top script until all sub processes are done
-trap '' SIGTERM
+  # Don't exit top script until all subprocesses are done.
+  trap '' SIGTERM
 
-# Start stunnel
-(
-  # We expect stunnel to run in the foreground.
-  echo 'buildpack=pgbouncer at=stunnel-start'
-  vendor/stunnel/bin/stunnel vendor/stunnel/stunnel-pgbouncer.conf
-  echo 'stunnel' >$psmgr
-) &
+  # This read will block the process waiting on a msg to be put into the
+  # fifo. If any of the processes defined above should exit, a msg will be
+  # put into the fifo causing the read operation to un-block. The process
+  # putting the msg into the fifo will use it's process name as a msg so that
+  # we can print the offending process to stdout.
+  declare exit_process
+  read exit_process < "$psmgr"
+  at "exit process=$exit_process"
 
-# Start PGBouncer
-(
-  # We expect pgbouncer to run in the foreground.
-  echo 'buildpack=pgbouncer at=pgbouncer-start'
-  vendor/pgbouncer/bin/pgbouncer vendor/pgbouncer/pgbouncer.ini
-  echo 'pgbouncer' >$psmgr
-) &
+  # Remove the FIFO. This allows following writes to simply create a file,
+  # rather than blocking because there's nothing reading the other end.
+  rm -f "$psmgr"
 
-# Start App Server
-(
-  # Take the command passed to this bin and start it.
-  # E.g. bin/start-pgbouncer-stunnel bundle exec unicorn -c config/unicorn.rb
-  echo "buildpack=pgbouncer at=app-start cmd=$*"
-  "$@"
-  echo 'app' >$psmgr
-) &
-subshell=$!
+  # Clean up any running processes.
+  # SIGTERM application just in case something else crashed.
+  # If the dyno is shutting down, then SIGTERM has already been sent.
+  at "kill-app pid=$pid"
+  kill -SIGTERM $pid
 
-# This read will block the process waiting on a msg to be put into the
-# fifo. If any of the processes defined above should exit, a msg will be
-# put into the fifo causing the read operation to un-block. The process
-# putting the msg into the fifo will use it's process name as a msg so that
-# we can print the offending process to stdout.
-read exit_process <$psmgr
-echo "buildpack=pgbouncer at=exit process=$exit_process"
+  # Wait for the app to finish.
+  at "wait-app pid=$pid"
+  wait $pid
 
-# Clean up any running processes
-# SIGTERM application just in case something else crashed
-echo "Sending SIGTERM to application"
-kill -SIGTERM $subshell
+  # Kill the auxiliary processes.
+  # Send each one SIGHUP which will be translated by the trap in aux-start.
+  declare name
+  for name in "${!pids[*]}"; do
+    at "kill-aux name=$name pid=${pids[$name]} signal=${signals[$name]}"
+    kill -SIGHUP "${pids[$name]}"
+  done
+}
 
-wait %3
+config-gen() {
+  # Generate config files
+  at config-gen-start
+  source bin/gen-pgbouncer-conf.sh
+  at config-gen-end
 
-echo "Sending SIGINT to pgbouncer"
-pkill -SIGINT pgbouncer
+  # Overwrite config vars with pgbouncer targets
+  POSTGRES_URLS=${PGBOUNCER_URLS:-DATABASE_URL}
 
-echo "Sending SIGINT to stunnel"
-pkill -SIGINT stunnel
+  for POSTGRES_URL in $POSTGRES_URLS; do
+    at "config-gen-override $POSTGRES_URL"
+    eval "$POSTGRES_URL=\$${POSTGRES_URL}_PGBOUNCER"
+  done
+}
 
-exit 1
+aux-start() {
+  declare name=$1 signal=$2
+  shift 2
+
+  (
+    at "$name-start"
+
+    # Ignore SIGTERM; this is inherited by the child process.
+    trap '' SIGTERM
+
+    # Start child in the background.
+    "$@" &
+
+    # Translate SIGHUP to the appropriate signal to stop the child
+    # (anything except SIGTERM which is ignored). Since this doesn't
+    # exit, it won't cancel the wait.
+    trap "kill -$signal $!" SIGHUP
+
+    # Wait for child to finish, either by crash or by $signal
+    wait
+
+    # Notify FIFO if this finishes first
+    echo "$name" > "$psmgr"
+
+    at "$name-end"
+  ) &
+
+  pids[$name]=$!
+  signals[$name]=$signal
+  at "$name-launched pid=$! signal=$signal"
+}
+
+app-start() {
+  declare name=app signal=$1
+  shift
+
+  (
+    at "$name-start"
+
+    # Start child in the background. This is before the trap because
+    # the app needs to be able to receive when the dyno broadcasts
+    # SIGTERM on shutdown.
+    "$@" &
+
+    # Translate SIGHUP/SIGTERM to the appropriate signal to stop the child
+    # (probably SIGTERM in this case). Since this doesn't exit, it won't
+    # cancel the wait.
+    trap "kill -$signal $!" SIGHUP SIGTERM
+
+    # Wait for the app to finish, either by crash or by $signal
+    wait
+
+    # Notify FIFO if this finishes first
+    echo "$name" > $psmgr
+
+    at "$name-end"
+  ) &
+
+  at "$name-launched pid=$!"
+}
+
+at() {
+  echo "buildpack=pgbouncer at=$*"
+}
+
+[[ "$0" != "$BASH_SOURCE" ]] || main "$@"
