Add heroku-22 support and upgrade pg-bouncer to 1.17 (#1)
* Add support for Heroku-22 (#161)

Binary generated using `make build-heroku-22`.

GUS-W-10346720.

* Release v0.10.0 (#162)

To pick up #161.

GUS-W-10346720.

* Update to pgbouncer v1.17.0 on Heroku-22 (#166)

To fix crashes/seg faults seen on Heroku-22 due to Ubuntu 22.04
now shipping with OpenSSL 3.

See:
https://www.pgbouncer.org/2022/03/pgbouncer-1-17-0
https://www.pgbouncer.org/changelog.html#pgbouncer-117x

The other stacks remain on pgbouncer 1.14.0 for now, until #150 (the reason
an earlier upgrade to pgbouncer was rolled back) can be investigated.

#165 is also open for improving the CI of this repo (since it didn't catch these
crashes), though fixing that is out of the scope of this PR, as we just need to
stop the crashes for now.

Fixes #164.
GUS-W-11319779.

* Patch sigterm for version 1.17.0 too (#169)

* Adds the missing patchfile for 1.17.0, meaning sigterm is now correctly patched for that version too.
* Removes the "default" patchfiles directory and makes the per-version directories mandatory, so future releases can't accidentally forget to add a new patchfile.
* Removes the patchfile for pgbouncer 1.7 and 1.13.0 since those versions are no longer built.

Closes #150.
Closes #168.
GUS-W-11700066.

* Update pgbouncer to v1.17.0 for Heroku-18 and Heroku-20 (#170)

For parity with Heroku-22 (thereby reducing differences between stacks, so
there is one fewer thing to think about when upgrading stacks), now that the
cause of #150 is understood and fixed.

https://www.pgbouncer.org/changelog.html#pgbouncer-117x

Binaries generated using `make build-heroku-18 build-heroku-20`.

* Convert to Github Actions (#172)

* Allow SSL certificate usage for database connections

* remake binaries

Co-authored-by: Ed Morley <501702+edmorley@users.noreply.github.com>
Co-authored-by: Ken Barber <ken@bob.sh>
Co-authored-by: teckwan <wong.teck.wan@outlook.com>
Co-authored-by: Pierre-Olivier Maugis <pierre-olivier.maugis@klaxit.com>

diff --git a/support/pgbouncer-build b/support/pgbouncer-build
--- a/support/pgbouncer-build
+++ b/support/pgbouncer-build
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-set -e
+set -euo pipefail
 
-PGBOUNCER_VERSION=${PGBOUNCER_VERSION-1.14.0}
+PGBOUNCER_VERSION=${PGBOUNCER_VERSION-1.17.0}
 
 pgbouncer_tarball_url=https://www.pgbouncer.org/downloads/files/${PGBOUNCER_VERSION}/pgbouncer-${PGBOUNCER_VERSION}.tar.gz
 
@@ -18,7 +18,8 @@ if [ -d "/buildpack/support/patchfiles/${PGBOUNCER_VERSION}" ]
 then
 		PATCHFILES=$(find /buildpack/support/patchfiles/"${PGBOUNCER_VERSION}" -name '*.patch')
 else
-		PATCHFILES=$(find /buildpack/support/patchfiles/default -name '*.patch')
+		echo "Missing patchfiles directory for ${PGBOUNCER_VERSION}!" >&2
+		exit 1
 fi
 
 (
